# Generated by Django 4.1.2 on 2023-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=255)),
                ('Option', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Level', models.CharField(max_length=255)),
                ('Expired', models.DateField()),
            ],
        ),
    ]
