# Generated by Django 4.1.2 on 2023-02-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='Request',
            field=models.CharField(default='Exam card', max_length=255),
        ),
    ]
