# Generated by Django 4.1.2 on 2023-02-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_studentdata_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='Gender',
            field=models.CharField(default='Male', max_length=255),
        ),
    ]
