# Generated by Django 4.1.2 on 2023-02-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0004_studentdata_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Gender',
            field=models.CharField(default='male', max_length=255),
        ),
    ]
